version: 2
updates:
- package-ecosystem: pip
  directory: "/app"
  schedule:
    interval: daily
    time: "07:00"
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: daily
    time: "07:00"
